version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - export LANG=en_US.UTF-8
      - mvn dependency:go-offline
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - ls -l
      - mvn clean package -DskipTests
      - ls -l target
      - mv target/*.jar application.jar
  post_build:
    commands:
      - ls -l $CODEBUILD_SRC_DIR
artifacts:
  files:
    - application.jar
    - Procfile
    - target/**/*
