version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REPOSITORY_URI: "650251708051.dkr.ecr.us-east-1.amazonaws.com/mi-micro-java"
    CONTAINER_NAME: "mi-micro-java"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - export LANG=en_US.UTF-8
      - mvn dependency:go-offline
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - ls -l
      - mvn clean package -DskipTests
      - ls -l target
      - mv target/*.jar application.jar
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$CONTAINER_NAME-latest .
      - docker tag $REPOSITORY_URI:$CONTAINER_NAME-latest $REPOSITORY_URI:$CONTAINER_NAME-$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$CONTAINER_NAME-latest
      - docker push $REPOSITORY_URI:$CONTAINER_NAME-$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - application.jar
    - Procfile
    - target/**/*
